---
- hosts: localhost
  tasks:
  - name: stop current running container
    command: /usr/local/bin/docker stop mycapstone
    ignore_errors: yes
  
  - name: remove the stopped container
    command: /usr/local/bin/docker rm mycapstone
    ignore_errors: yes

  - name: remove the docker image
    command: /usr/local/bin/docker rmi capstoneapp
    ignore_errors: yes

  - name: build a docker image
    command: /usr/local/bin/docker build -t capstoneapp . 

  - name: run the container from the built image
    command: /usr/local/bin/docker run -d -p 8098:8080 --name mycapstone capstoneapp

  - name: build mysql table
    command: docker exec mycapstone service mysql start
  - name: creating user
    command: docker exec mycapstone mysql -e "CREATE USER 'jwt'@'localhost' IDENTIFIED BY 'Password@123';"
  - name: granting permissions
    command: docker exec mycapstone mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'jwt'@'localhost' WITH GRANT OPTION;" 
  - name: exit
    command: docker exec mycapstone mysql -e "exit"
  - name: create table
    command: docker exec mycapstone mysql -e "create database jwt; use jwt; create table USER(first_name varchar(20),last_name varchar(20),email varchar(255),username varchar(20) PRIMARY KEY,password varchar(20), regdate date); create table ticket_details(fname varchar(20) not null,lname varchar(20),age varchar(20) not null,dob date not null,phone varchar(50) not null primary key,type varchar(20) not null,fromloc varchar(20) not null,toloc varchar(20) not null,price varchar(20) not null,ticket varchar(100) not null);"

       